### ISSUE TITLE
Objects that have no __name__

### ISSUE THREAD

**Issue by brl0** [sloria/konch#105]
Opening an issue for this problem since it has not yet been solved and is separate from the other I reported.
When importing objects that have no __name__ attribute, an AttributeError occurs when iterating over the context objects to build up the context dict.  Also, there is not necessarily a guarantee that a variable name matches its __name__ attribute anyway.
The only approach I have found is to iterate over the dir of the import .konchrc module and check if the object is in the context list.  While working on #99, it seemed natural to do this inside the `get_config` function that I was creating.
I think this issue may be easier to resolve once #99 is resolved, and possibly along with it.
One of my closed PRs has a test for this issue.

**Comment by sloria** [comment]
This case is now handled by showing an error that tells the user to use a context dictionary instead of a list.

**Comment by brl0** [comment]
That works too, thanks!  This is something I had considered, but didn't want to blow up any existing user configs using lists.  Shouldn't be a big deal though, this is easy to fix.

**Comment by sloria** [comment]
Well, it was already blowing up...now it just blows up in a helpful way =)
