### ISSUE TITLE
ptpython has its own user config defined default, which konch doesn't use.

### ISSUE THREAD

**Issue by nasyxx** [sloria/konch#16]
ptpython has its own user config file in "~/.ptpython/config", defined as `configure`. When it starts, it will first read the user's default configuration.

https://github.com/jonathanslenders/ptpython/blob/d00f8d454fe2b94c499869e6677cce7a22601fc4/ptpython/entry_points/run_ptipython.py#L81-L92

I think that konch should read the user's config first and then overwrite with konch configuration. Or add a method to use the user's config and then overwrite with konch configuration.

**Comment by sloria** [comment]
If `ptpython` reads `~/.ptpython/config`, then konch should probably do that too when `ptpython` is the selected shell.

I would certainly review/merge a PR for this! =)

**Comment by pycadelic** [comment]
https://github.com/sloria/konch/pull/51

**Comment by sloria** [comment]
This is fixed in 3.0.0

**Comment by nasyxx** [comment]
So glad that this issue has been resolved, thank you very much.
