### ISSUE TITLE
RFC: Output informational messages to stderr

### ISSUE THREAD

**Issue by sloria** [sloria/konch#66]
Common wisdom is to use `stderr` for messaging (including informational messages) and `stdout` only for operational output in order to support piping and redirection flows. Should we do it for konch?

## Articles

* [12 Factor CLI Apps](https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46) (section 4)
* [CLI Design: handling output messages](https://julio.meroh.net/2013/09/cli-design-handling-output-messages.html)
* [When to use STDERR instead of STDOUT](https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout)

## Examples

The following CLIs write informational messages (non-error, non-warning) to `stderr`:

* `python` (REPL) - All output goes to stderr
* `docker-compose` - See https://github.com/docker/compose/issues/2115#issuecomment-193420167 . But there's a proposal to change this: https://github.com/docker/compose/issues/6078 .
* `gpg`
* [black](https://github.com/ambv/black/blob/bc7e5c949fa14da0a0174354a83567303bafb648/black.py#L74)
* heroku-cli
* `curl`

## Counterexamples

The following CLIs write informational messages to stdout.

* `ipython`
* `brew` 
* `yarn` and `npm`
* `git`, e.g. `git init` writes "Initialized empty Git repository" to stdout
* `pre-commit`
* `ansible`

## Other considerations

~~If we do this, we'd want some way to distinguish errors vs. warnings vs. info messages. [This article](https://julio.meroh.net/2013/09/cli-design-handling-output-messages.html) suggests two styles:~~

EDIT: We do this now.

> The first style you can use is to write the ERROR and WARNING words in error and warning messages respectively, and leave informational messages alone. For example:

```bash
myprogram: ERROR: Must provide at least one URL.
myprogram: WARNING: Failed to connect to server; skipping.
myprogram: Connecting to http://www.example.com/...
```

> The second style you can use is to write a single letter indicating the severity of the message and add that letter to every single message printed by the program. For example:

```bash
myprogram: E: Must provide at least one URL.
myprogram: W: Failed to connect to server; skipping.
myprogram: I: Connecting to http://www.example.com/...
```

**Comment by sloria** [comment]
Closing for lack of interest

**Comment by ElusiveByte** [comment]
This behavior breaks a lot of DevOps tools which report info messages as errors

**Comment by sloria** [comment]
@ElusiveByte are you suggesting that konch should output to stderr?

**Comment by ElusiveByte** [comment]
no sorry, I mean the opposite. from my experience it should output to stdout unless it's a real error. otherwise, tools like azure DevOps pipelines will report a failed build based on info messages

**Comment by sloria** [comment]
Oh, interesting. That's surprising given the number of popular tools that output info messages to stderr.

On a related note: do we ever expect people to run `konch` in CI pipelines?

Anyway, if there's a possibility of breaking CI pipelines, that's probably reason enough not to move forward with this. There wasn't enough interest in the first place to change the current behavior. We can always revisit
