### ISSUE TITLE
add bpython-curses as option to KONCH_SHELL

### ISSUE THREAD

**Issue by goandbuild** [sloria/konch#78]
Please refer to issue: https://github.com/bpython/bpython/issues/741
Cause: https://github.com/bpython/bpython/issues/640

With BPython, currently SQLAlchemy commit operations don't work as expected. `bpython-curses` which comes bundled with `bpython` solves this.

**Comment by sloria** [comment]
I've transferred this to konch since this is likely something that should be added as a `Shell` class. PRs welcome.

**Comment by goandbuild** [comment]
How can I remove color around `Context:` text which Konch passes to shell?

![screenshot from 2019-02-18 20-26-26](https://user-images.githubusercontent.com/26769888/52959296-dfe8fd00-33bb-11e9-9193-396ffe9fbc2d.png)

(I'm new to all this, thanks!)

**Comment by sloria** [comment]
You can set the `NO_COLOR` envvar to remove coloring.

```
NO_COLOR=1 konch -s bpy
```
